#REST
##login
POST http://localhost:9092/admin/login
Content-Type: application/json

{
    "email": "authen-c@rmutp.ac.th",
    "password": "P@ssw0rd",
    "rememberMe": false
}

###Register
POST http://localhost:9092/admin/register-admin
Content-Type: application/json

    {
        "email": "authen-c@rmutp.ac.th",
        "firstname": "Authen",
        "lastname": "Chungthaisong",
        "password": "P@ssw0rd"
    }
###Forgot Password
POST http://localhost:9092/admin/forgot-password
Content-Type: application/json

{
    "email": "authen-c@rmutp.ac.th"
}

### Profile
GET http://localhost:9092/admin/users/me
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiaWF0IjoxNzg3NDE5MDE5LCJleHAiOjE3OTAwMTEwMTl9.zKiWBHad0p2e52i17a2Xxz11JTK28UNvU2GIiRlqLnQ
Content-Type: application/json