services: 
  db:
    image: postgres:latest
    container_name: 69-s2-admin
    ports:
      - 54322:80
    environment:
      - POSTGRES_PASSWORD=P@ssw0rd
      - POSTGRES_USER=then
      # - POSTGRES_DB=postgres
