services: 
  db:
    image: dpage/pgadmin4:latest
    container_name: 69-s2-admin
    ports:
      - 8080:5432
    environment:
      - POSTGRES_PASSWORD=P@ssw0rd
      - POSTGRES_USER=then
      # - POSTGRES_DB=postgres