services: 
  page:
    image: dpage/pgadmin4:latest
    container_name: 69-s2-admin
    ports:
      - 8080:5433
    environment:
      - PGADMIN_DEFAULT_PASSWORD=P@ssw0rd
      - PGADMIN_DEFAULT_EMAIL=authen-c@rmutp.ac.th
  db:
    image: postgres:16-alpine
    container_name: 69-s2-db
    ports:
      - 54320:5432
    environment:
      - POSTGRES_PASSWORD=P@ssw0rd
      - POSTGRES_USER=authen
      - POSTGRES_DB=MY_DB